name: 'Preview Deployment'
description: 'Deploy the app to a preview environment'

inputs:
  app-definition-path:
    description: 'The path to the app definition file'
    required: true
    default: 'app-definition.yaml'

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y wget curl 
        # install yq
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

    - name: Deploy app
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      shell: bash
      run: |
        echo "pr id is ${{ github.event.pull_request.id }}"
        echo "content of app definition is $APP_DEF"

    - name: read comment
      if: github.event_name == 'issue_comment' && github.event.action == 'created'
      shell: bash
      run: |
        echo "comment is ${{ github.event.comment.body }}"
        echo "content of app definition is $APP_DEF"
