name: 'Preview Deployment'
description: 'Deploy the app to a preview environment'

inputs:
  app-definition-path:
    description: 'The path to the app definition file'
    required: true
    default: 'app-definition.yaml'

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: install dependencies
      shell: bash
      run: ${{ github.action_path }}/scripts/install-deps.sh

    - name: Deploy app
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      shell: bash
      run: ${{ github.action_path }}/scripts/deploy-app.sh

    - name: read comment
      if: github.event_name == 'pull_request_review_comment' && github.event.action == 'created'
      shell: bash
      run: ${{ github.action_path }}/scripts/read-comment.sh

