name: preview deploy

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  pull_request_review_comment:
    types:
      - created
      - edited

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Preview Deployment
        uses: ./.github/actions/preview-deployment
        with:
          app-definition-path: './.github/app-definitions/test.yaml'
      - name: preview deploy ts
        uses: ./.github/actions/pd
        with:
          app-definition-path: './.github/app-definitions/test.yaml'